### ISSUE TITLE
synchronize package requirements between github and conda forge geokit-feedstock

### ISSUE THREAD

**Issue by phil-fzj** [FZJ-IEK3-VSA/geokit#11]
Currently the conda forge geokit-feedstock has different requirements than what is specified in the geokit github repo. Especially regarding gdal
**geokit-feedstock**
```
requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-git
    - setuptools
  run:
    - python >={{ python_min }}
    - pytest
    - pytest-cov
    - pylint
    - autopep8
    - jupyter
    - notebook
    - jupyterlab
    - pip
    - matplotlib
    - descartes
    - pandas
    - numpy <1.24
    - scipy
    - scikit-learn
    - gdal >=3.4.2,<=3.4.3
    - smopy
    - geopandas

```

**geokit repo (this repo)**
```
    install_requires=[
        "gdal>=2.4.0, ==3.4.*",
        "numpy",
        "descartes",
        "pandas",
        "scipy",
        "matplotlib",
        "smopy",
    ]
```
